version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: web_garage
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    command: -c listen_addresses='*'

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    restart: unless-stopped
    command: http host.docker.internal:8080
    environment:
      NGROK_AUTHTOKEN: "35p6W4iLprFJO4HJsfrf7j8l0Ys_KwvJhsYrEK6DBHNZQWB4"

volumes:
  pgdata:
